[tool.poetry]
name = "pylox"
version = "0.1.0"
description = ""
authors = ["iceice666 <iceice666@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
result = "^0.17.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
